spring:
  sql:
    init:
      mode: always
      encoding: UTF-8
      continue-on-error: true
      schema-locations: classpath:db/related.sql
  datasource:
    url: jdbc:postgresql://localhost:5432/worklenz_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true    # 开启驼峰命名

  mybatis-plus:
    type-handlers-package: com.cityu.srcspring.handler
